### ISSUE TITLE
QV score is lower after polishing

### ISSUE THREAD

**Issue by tothuhien** [Maggi-Chen/Inspector#8]
Hi,
I have an assembly built with Flye, and then I polish it with pepper. Using inspector to evaluate the QV score, I have a lower QV after polishing. Have you had this issue before and do you know why? Thanks for your help.
Hien

**Comment by afvrbanac** [comment]
@tothuhien I also see this, but I polished with Medaka followed by Homopolish (which does polishing with closely related genomes). While my Homopolish assemblies have better CheckM scores for completeness, they have much worse QVs than Medaka polishing only. I suspect it is because the raw reads differ more from the corrected polished assembly. Maybe that is what's happening in your case?
